### ISSUE TITLE
Compilation Error on large watchface

### ISSUE THREAD

**Issue by yschimke** [Splitties/WffDsl#19]
I can refactor, but reporting this as it was confusing

```
exception: exception: java.lang.RuntimeException: Error generating class file xxx.class (compiled from [/Users/yschimke/StudioProjects/xxx]): Method too large: xxxx.xxx (Lsplitties/wff/WatchFaceDsl;)Ljava/lang/Object;
exception: 	at org.jetbrains.kotlin.codegen.ClassFileFactory$OutputClassFile.asByteArray(ClassFileFactory.java:310)
exception: 	at org.jetbrains.kotlin.cli.common.output.OutputUtilsKt.writeAll(outputUtils.kt:33)
exception: 	at org.jetbrains.kotlin.cli.common.output.OutputUtilsKt.writeAllTo(outputUtils.kt:47)
exception: 	at org.jetbrains.kotlin.cli.common.output.OutputUtilsKt.writeAll(outputUtils.kt:52)
```

**Comment by LouisCAD** [comment]
Weird. I'm wondering if K2 will have the same limitation.

Out of curiosity, how many LoC is the problematic method?

**Comment by yschimke** [comment]
750 for entire file including imports
